#!/bin/sh

# The config file and the notification config files are as per the following paths.
# These can be configured as per your svn settings.

REPOS="$1"
REV="$2"

CONFIGFILE="/opt/svn/svn-controls/svn_notification.cfg"

/opt/svn/svn-controls/SVNPostCommit.py "$REPOS" $REV $CONFIGFILE

exit $?
